name: Convert Encoding to UTF-8

on:
  push:
    branches:
      - 'master'  # master に push されたときに実行

jobs:
  convert-encoding:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install uchardet and iconv
        run: |
          sudo apt-get update
          sudo apt-get install -y uchardet

      - name: Find and convert .cpp and .h files to UTF-8
        id: convert
        run: |
          echo "modified_files=" >> $GITHUB_OUTPUT
          report_file="converted_files.txt"
          > "$report_file"

          find . -type f \( -name "*.cpp" -o -name "*.h" \) | while read file; do
            encoding=$(uchardet "$file")

            # uchardet が失敗して空文字を返すことがある
            if [ -z "$encoding" ]; then
              echo "エンコード判定失敗: $file"
              continue
            fi

            if [ "$encoding" != "UTF-8" ]; then
              echo "Converting $file from $encoding to UTF-8"

              if iconv -f "$encoding" -t utf-8 "$file" -o "$file.utf8"; then
                mv "$file.utf8" "$file"
                echo "$file" >> "$report_file"
              else
                echo "変換失敗: $file ($encoding)"
                rm -f "$file.utf8"
              fi
            fi
          done

          if [ -s "$report_file" ]; then
            echo "以下のファイルをUTF-8に変換しました:"
            cat "$report_file"
            echo "modified_files=$(cat "$report_file" | paste -sd ',' -)" >> $GITHUB_OUTPUT
          else
            echo "UTF-8変換が必要なファイルはありませんでした。"
          fi

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git diff --cached --quiet || git commit -m "Convert .cpp/.h files to UTF-8"
          git push
